-- LEGACY INITIAL SETUP. If you already ran this before V11, DO NOT RUN IT AGAIN. Run supabase-v11-migration.sql instead.
-- Encita Lying-in Clinic CMS
-- Run this once in Supabase > SQL Editor.

create table if not exists public.clinic_schedule (
  id bigint generated by default as identity primary key,
  badge_top text not null default 'Clinic',
  badge_main text not null default 'Today',
  title text not null default 'Who’s on duty today?',
  provider_name text,
  specialty text,
  schedule_time text,
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_reviews (
  id bigint generated by default as identity primary key,
  reviewer_name text not null,
  review_date date,
  review_text text not null,
  source_label text not null default 'Facebook recommendation',
  source_url text,
  sort_order integer not null default 100,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clinic_news (
  id bigint generated by default as identity primary key,
  title text not null,
  caption text,
  image_url text,
  published_date date not null default current_date,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.clinic_schedule enable row level security;
alter table public.clinic_reviews enable row level security;
alter table public.clinic_news enable row level security;

-- Public website can read published/active content.
drop policy if exists "Public can read active clinic schedule" on public.clinic_schedule;
create policy "Public can read active clinic schedule" on public.clinic_schedule for select to anon, authenticated using (is_active = true or auth.role() = 'authenticated');
drop policy if exists "Public can read published clinic reviews" on public.clinic_reviews;
create policy "Public can read published clinic reviews" on public.clinic_reviews for select to anon, authenticated using (is_published = true or auth.role() = 'authenticated');
drop policy if exists "Public can read published clinic news" on public.clinic_news;
create policy "Public can read published clinic news" on public.clinic_news for select to anon, authenticated using (is_published = true or auth.role() = 'authenticated');

-- Authenticated clinic admins can manage CMS content.
drop policy if exists "Authenticated manage clinic schedule" on public.clinic_schedule;
create policy "Authenticated manage clinic schedule" on public.clinic_schedule for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated manage clinic reviews" on public.clinic_reviews;
create policy "Authenticated manage clinic reviews" on public.clinic_reviews for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated manage clinic news" on public.clinic_news;
create policy "Authenticated manage clinic news" on public.clinic_news for all to authenticated using (true) with check (true);

-- Public bucket for website news images. Only signed-in admins can upload/change files.
insert into storage.buckets (id,name,public) values ('news-media','news-media',true)
on conflict (id) do update set public=true;

drop policy if exists "Public read Encita news media" on storage.objects;
create policy "Public read Encita news media" on storage.objects for select to public using (bucket_id='news-media');
drop policy if exists "Admin upload Encita news media" on storage.objects;
create policy "Admin upload Encita news media" on storage.objects for insert to authenticated with check (bucket_id='news-media');
drop policy if exists "Admin update Encita news media" on storage.objects;
create policy "Admin update Encita news media" on storage.objects for update to authenticated using (bucket_id='news-media') with check (bucket_id='news-media');
drop policy if exists "Admin delete Encita news media" on storage.objects;
create policy "Admin delete Encita news media" on storage.objects for delete to authenticated using (bucket_id='news-media');

insert into public.clinic_schedule (badge_top,badge_main,title,note,is_active)
select 'Clinic','Today','Who’s on duty today?','Provider availability may vary. Message us on Facebook or call ahead before visiting.',true
where not exists (select 1 from public.clinic_schedule);
