-- Encita V11 additive migration. Safe to run after the existing V7/V10 setup.
-- It does NOT drop existing reviews, news, schedules, users, or media.

-- Admin allow-list tied to Supabase Auth users.
create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now()
);
alter table public.admin_profiles enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_profiles a where a.user_id=auth.uid());
$$;
-- Approve the existing Encita administrator account if present.
insert into public.admin_profiles(user_id,email,display_name)
select id,email,'Encita Administrator' from auth.users where lower(email)=lower('hedrian226@gmail.com')
on conflict(user_id) do nothing;
drop policy if exists "Admins can read admin profiles" on public.admin_profiles;
create policy "Admins can read admin profiles" on public.admin_profiles for select to authenticated using (public.is_admin());

-- Add richer review/news fields without losing existing data.
alter table public.clinic_reviews add column if not exists rating integer not null default 5;
alter table public.clinic_reviews add column if not exists is_featured boolean not null default false;
alter table public.clinic_reviews add column if not exists is_deleted boolean not null default false;
alter table public.clinic_reviews add column if not exists deleted_at timestamptz;
alter table public.clinic_news add column if not exists category text default 'Clinic Update';
alter table public.clinic_news add column if not exists image_urls text[] not null default '{}';
alter table public.clinic_news add column if not exists is_featured boolean not null default false;
alter table public.clinic_news add column if not exists is_deleted boolean not null default false;
alter table public.clinic_news add column if not exists deleted_at timestamptz;
update public.clinic_news set image_urls=array[image_url] where image_url is not null and cardinality(image_urls)=0;

create table if not exists public.clinic_appointments (
 id bigint generated by default as identity primary key, patient_name text not null, phone text not null, email text,
 service text not null, preferred_date date, preferred_time time, notes text, status text not null default 'pending',
 source text default 'website', is_deleted boolean not null default false, deleted_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_announcements (
 id bigint generated by default as identity primary key, title text not null, message text, link_url text,
 starts_at timestamptz, ends_at timestamptz, priority integer not null default 100, is_published boolean not null default true,
 is_deleted boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_team (
 id bigint generated by default as identity primary key, name text not null, role text, specialty text, schedule_text text, bio text,
 photo_url text, sort_order integer not null default 100, is_published boolean not null default true,
 is_deleted boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_gallery (
 id bigint generated by default as identity primary key, category text, caption text, image_url text not null,
 sort_order integer not null default 100, is_published boolean not null default true,
 is_deleted boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_faqs (
 id bigint generated by default as identity primary key, question text not null, answer text not null,
 sort_order integer not null default 100, is_published boolean not null default true,
 is_deleted boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_services (
 id bigint generated by default as identity primary key, name text not null, category text, description text, availability text,
 sort_order integer not null default 100, is_published boolean not null default true,
 is_deleted boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.clinic_analytics (
 id bigint generated by default as identity primary key, event_name text not null, path text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.clinic_activity_log (
 id bigint generated by default as identity primary key, admin_user uuid default auth.uid(), action text not null, entity text not null,
 entity_id text, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

alter table public.clinic_appointments enable row level security; alter table public.clinic_announcements enable row level security;
alter table public.clinic_team enable row level security; alter table public.clinic_gallery enable row level security;
alter table public.clinic_faqs enable row level security; alter table public.clinic_services enable row level security;
alter table public.clinic_analytics enable row level security; alter table public.clinic_activity_log enable row level security;

-- Replace broad authenticated CMS access with approved-admin access.
drop policy if exists "Authenticated manage clinic schedule" on public.clinic_schedule;
drop policy if exists "Authenticated manage clinic reviews" on public.clinic_reviews;
drop policy if exists "Authenticated manage clinic news" on public.clinic_news;
drop policy if exists "Admins manage clinic schedule" on public.clinic_schedule;
create policy "Admins manage clinic schedule" on public.clinic_schedule for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins manage clinic reviews" on public.clinic_reviews;
create policy "Admins manage clinic reviews" on public.clinic_reviews for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins manage clinic news" on public.clinic_news;
create policy "Admins manage clinic news" on public.clinic_news for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Tighten public review/news reads to exclude Trash.
drop policy if exists "Public can read published clinic reviews" on public.clinic_reviews;
create policy "Public can read published clinic reviews" on public.clinic_reviews for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
drop policy if exists "Public can read published clinic news" on public.clinic_news;
create policy "Public can read published clinic news" on public.clinic_news for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());

-- Public content policies + admin management.
create policy "Public read announcements" on public.clinic_announcements for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
create policy "Admins manage announcements" on public.clinic_announcements for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Public read team" on public.clinic_team for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
create policy "Admins manage team" on public.clinic_team for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Public read gallery" on public.clinic_gallery for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
create policy "Admins manage gallery" on public.clinic_gallery for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Public read faqs" on public.clinic_faqs for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
create policy "Admins manage faqs" on public.clinic_faqs for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Public read services" on public.clinic_services for select to anon,authenticated using ((is_published=true and is_deleted=false) or public.is_admin());
create policy "Admins manage services" on public.clinic_services for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- Appointment: visitors may submit, only admins can read/update.
create policy "Visitors submit appointments" on public.clinic_appointments for insert to anon,authenticated with check (status='pending' and is_deleted=false);
create policy "Admins manage appointments" on public.clinic_appointments for all to authenticated using(public.is_admin()) with check(public.is_admin());
-- Privacy-light analytics: visitors may write event records; only admins can read.
create policy "Visitors write analytics" on public.clinic_analytics for insert to anon,authenticated with check(true);
create policy "Admins read analytics" on public.clinic_analytics for select to authenticated using(public.is_admin());
create policy "Admins manage activity log" on public.clinic_activity_log for all to authenticated using(public.is_admin()) with check(public.is_admin());

-- Shared public media bucket for team/gallery/news CMS uploads.
insert into storage.buckets(id,name,public) values('cms-media','cms-media',true) on conflict(id) do update set public=true;
drop policy if exists "Public read Encita CMS media" on storage.objects;
create policy "Public read Encita CMS media" on storage.objects for select to public using(bucket_id='cms-media');
drop policy if exists "Admins insert Encita CMS media" on storage.objects;
create policy "Admins insert Encita CMS media" on storage.objects for insert to authenticated with check(bucket_id='cms-media' and public.is_admin());
drop policy if exists "Admins update Encita CMS media" on storage.objects;
create policy "Admins update Encita CMS media" on storage.objects for update to authenticated using(bucket_id='cms-media' and public.is_admin()) with check(bucket_id='cms-media' and public.is_admin());
drop policy if exists "Admins delete Encita CMS media" on storage.objects;
create policy "Admins delete Encita CMS media" on storage.objects for delete to authenticated using(bucket_id='cms-media' and public.is_admin());
